# Generated by Django 3.1.2 on 2021-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_func', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reptile_reg',
            name='url',
            field=models.CharField(max_length=256, verbose_name='初始URl'),
        ),
    ]
