"""
Django settings for hamob2 project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pm3g8m(^a-_w3urr8l*5f840w4d228ex=2)lcv-mrjmm4zbpeb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'rbac.templatetags',
    'stark.apps.StarkConfig',
    'rbac.apps.RbacConfig',
    'hardmanage.apps.HardmanageConfig',
    'business_presen.apps.BusinessPresenConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middleware.rbac.RbacMiddleware',
]

ROOT_URLCONF = 'hamob2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hamob2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
'yun12': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '111.4.114.74',
        'NAME': 'blxxxtjc',
        'USER': 'hamob',
        'PASSWORD': '123@asdF',
        'PORT': 33012,
        'OPTIONS': {'charset': 'utf8mb4'},
        'CONN_MAX_AGE': None,
    },
    'yun21': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '111.4.114.74',
        'NAME': 'blxxxtjc',
        'USER': 'hamob',
        'PASSWORD': 'hamobcom',
        'PORT': 13308,
        'OPTIONS': {'charset': 'utf8mb4'},
        'CONN_MAX_AGE': None,
    },
    'fc61': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '42.121.113.75',
        'NAME': 'blxxxtjc',
        'USER': 'hanbang',
        'PASSWORD': 'hamoB123!',
        'PORT': 13309,
        'OPTIONS': {'charset': 'utf8mb4'},
        'CONN_MAX_AGE': None,
    },
    'fc62': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '42.121.113.75',
        'NAME': 'blxxxtjc',
        'USER': 'hamob',
        'PASSWORD': '123@asdF',
        'PORT': 13362,
        'OPTIONS': {'charset': 'utf8mb4'},
        'CONN_MAX_AGE': None,
    },
    'default': {
    # 'hz37': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '192.168.3.19',
        'NAME': 'hamob',
        'USER': 'hamob',
        'PASSWORD': '123@asdF',
        'PORT': 3306,
        'OPTIONS': {'charset': 'utf8mb4', 'init_command': 'SET sql_mode="STRICT_TRANS_TABLES"'},
        'CONN_MAX_AGE': 60*60*6,
    },
    'orac119': {
    # 'default': {
        'ENGINE': 'django.db.backends.oracle',
        'HOST': '42.121.113.75',
        'NAME': 'ORCLCDB',
        'USER': 'c##hamob',
        'PASSWORD': 'qwe123asd',
        'PORT': 15119,
        'CONN_MAX_AGE': None,
        'OPTIONS': {
            'threaded': True, 'use_returning_into': False,
        },
    },
    'yun250': {
    # 'default': {
        'ENGINE': 'django.db.backends.oracle',
        'HOST': '111.4.114.74',
        'NAME': 'orcl3',
        'USER': 'hamob',
        'PASSWORD': 'qwe123asd',
        'PORT': 11521,
        'CONN_MAX_AGE': None,
        'OPTIONS': {
            'threaded': True,'use_returning_into': False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_URL = '/static/'
STATIC_URL = '/static/'
# ######################## crm业务相关配置 #############################
MAX_PRIVATE_CUSTOMER = 150


# ######################## rbac相关配置 #############################
USER_MODEL_PATH = "rbac.models.UserInfo"
MENU_SESSION_KEY = "u8fkksjdfkjsf"
PERMISSION_SESSION_KEY = "u8fkkasssjdfkjsfffff"

PERMISSION_VALID_URL = [
    '/login/',
    '/index/',
    '/logout/',
    '/admin/.*',
]
AUTO_DISCOVER_EXCLUDE = [
    '/admin/.*',
]

HARDNAME = 'harddetection'
HARDINFO = 'host_info'
##redis
REDIS_HOST='112.13.92.136'
REDIS_PORT = 6379
REDIS_DB = 1