# Generated by Django 3.1.2 on 2021-02-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='域名')),
                ('catchdate', models.DateField(blank=True, null=True)),
                ('ischeck', models.BooleanField(blank=True, null=True)),
                ('endcatchdate', models.DateField(blank=True, null=True, verbose_name='最后一次中标时间')),
                ('domaintype', models.BooleanField(blank=True, null=True)),
                ('insertdate', models.DateField(blank=True, null=True)),
                ('accpoint', models.CharField(blank=True, max_length=1, null=True)),
                ('sendtime', models.DateTimeField(blank=True, null=True)),
                ('lastsendtime', models.DateField(blank=True, null=True)),
                ('pv', models.FloatField(blank=True, null=True)),
                ('protocolid', models.CharField(blank=True, max_length=4, null=True)),
                ('iswhite', models.CharField(blank=True, max_length=1, null=True)),
                ('crawlflag', models.BooleanField(blank=True, null=True)),
                ('domainflag', models.BooleanField(blank=True, null=True)),
                ('phishing_flag_type', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='b_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('MonitorAdress', models.CharField(max_length=32)),
                ('DesFlow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Count_mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Monitor', models.BigIntegerField()),
                ('filescount', models.IntegerField()),
                ('reportURLNUM', models.IntegerField()),
                ('monitorURLNUM', models.BigIntegerField()),
                ('inserttime', models.DateField()),
                ('MonitorAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_mon_idc', to='hardmanage.idc')),
            ],
        ),
        migrations.CreateModel(
            name='Count_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Monitor', models.BigIntegerField(verbose_name='流量')),
                ('filescount', models.IntegerField()),
                ('reportURLNUM', models.IntegerField(verbose_name='疑似量')),
                ('monitorURLNUM', models.BigIntegerField(verbose_name='URL数量')),
                ('inserttime', models.DateTimeField()),
                ('MonitorAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardmanage.idc')),
            ],
        ),
    ]
